/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Andrés Lombo
 */
public class C_Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form C_Proveedor
     */
    public C_Proveedor() {
        initComponents();
        
        setTitle("Gestion de proveedores");

        try {
            setIconImage(new ImageIcon(getClass().getResource("/javax/swing/plaf/metal/icons/ocean/computer.gif")).getImage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jT_Cedula = new javax.swing.JTextField();
        jT_Nombre = new javax.swing.JTextField();
        jT_Apellido = new javax.swing.JTextField();
        jT_Celular = new javax.swing.JTextField();
        jT_DIreccion = new javax.swing.JTextField();
        jDate_Fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Proveedor = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        btn_Proveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 23, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bar_Log.jpg"))); // NOI18N

        btn_Volver.setBackground(new java.awt.Color(25, 23, 23));
        btn_Volver.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_Volver.setText("Volver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Volver)
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cedula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 161, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 206, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 251, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Celular");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 296, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha Nacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 346, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 388, -1, -1));

        jT_Cedula.setBackground(new java.awt.Color(255, 255, 255));
        jT_Cedula.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Cedula.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 160, 160, -1));

        jT_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jT_Nombre.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 205, 160, -1));

        jT_Apellido.setBackground(new java.awt.Color(255, 255, 255));
        jT_Apellido.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Apellido.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 250, 160, -1));

        jT_Celular.setBackground(new java.awt.Color(255, 255, 255));
        jT_Celular.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Celular.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 295, 160, -1));

        jT_DIreccion.setBackground(new java.awt.Color(255, 255, 255));
        jT_DIreccion.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_DIreccion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_DIreccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 387, 160, -1));

        jDate_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        jDate_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        jDate_Fecha.setDateFormatString("YYYY-MM-dd");
        jDate_Fecha.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jPanel1.add(jDate_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 340, 160, -1));

        jTable_Proveedor.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Proveedor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Proveedor.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Proveedor.setEnabled(false);
        jScrollPane1.setViewportView(jTable_Proveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 118, -1, 337));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ingresar nuevo Proveedor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        Total.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(51, 153, 0));
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 461, 481, -1));

        btn_Proveedor.setBackground(new java.awt.Color(0, 0, 0));
        btn_Proveedor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Proveedor.setForeground(new java.awt.Color(255, 255, 255));
        btn_Proveedor.setText("Crear");
        jPanel1.add(btn_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Total;
    public javax.swing.JButton btn_Proveedor;
    public javax.swing.JButton btn_Volver;
    public com.toedter.calendar.JDateChooser jDate_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jT_Apellido;
    public javax.swing.JTextField jT_Cedula;
    public javax.swing.JTextField jT_Celular;
    public javax.swing.JTextField jT_DIreccion;
    public javax.swing.JTextField jT_Nombre;
    public javax.swing.JTable jTable_Proveedor;
    // End of variables declaration//GEN-END:variables
}
