/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Andrés Lombo
 */
public class Carta extends javax.swing.JFrame {

    /**
     * Creates new form Carta
     */
    public Carta() {
        initComponents();
        
        setTitle("Gestion de carta");

        try {
            setIconImage(new ImageIcon(getClass().getResource("/javax/swing/plaf/metal/icons/ocean/computer.gif")).getImage());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_Volver1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable_Carta1 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable_Postre1 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable_Acompañante1 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable_Bebida1 = new javax.swing.JTable();
        btn_Carta1 = new javax.swing.JButton();
        btn_Acompañante1 = new javax.swing.JButton();
        btn_Bebida1 = new javax.swing.JButton();
        btn_Postre1 = new javax.swing.JButton();
        btn_Carta2 = new javax.swing.JButton();
        btn_Acompañante2 = new javax.swing.JButton();
        btn_Bebida2 = new javax.swing.JButton();
        btn_Postre2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Codigo = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Descripcion = new javax.swing.JTextArea();
        jTextField_Precio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(25, 23, 23));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bar_Log.jpg"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 97));

        btn_Volver1.setBackground(new java.awt.Color(25, 23, 23));
        btn_Volver1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Volver1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Volver1.setText("Volver");
        jPanel5.add(btn_Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        jTable_Carta1.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Carta1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Carta1.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Carta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable_Carta1);

        jPanel4.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 395, 421, 228));

        jTable_Postre1.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Postre1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Postre1.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Postre1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jTable_Postre1);

        jPanel4.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 641, 421, 251));

        jTable_Acompañante1.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Acompañante1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Acompañante1.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Acompañante1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(jTable_Acompañante1);

        jPanel4.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 395, 421, 228));

        jTable_Bebida1.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Bebida1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Bebida1.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Bebida1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(jTable_Bebida1);

        jPanel4.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 641, 421, 251));

        btn_Carta1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Carta1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Carta1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Carta1.setText("Cargar Carta");
        jPanel4.add(btn_Carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        btn_Acompañante1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Acompañante1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Acompañante1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Acompañante1.setText("Cargar Acompañante");
        jPanel4.add(btn_Acompañante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        btn_Bebida1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Bebida1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Bebida1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bebida1.setText("Cargar bebida");
        jPanel4.add(btn_Bebida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        btn_Postre1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Postre1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Postre1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Postre1.setText("Cargar postre");
        jPanel4.add(btn_Postre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        btn_Carta2.setBackground(new java.awt.Color(0, 0, 0));
        btn_Carta2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Carta2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Carta2.setText("Actualizar carta");
        jPanel4.add(btn_Carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        btn_Acompañante2.setBackground(new java.awt.Color(0, 0, 0));
        btn_Acompañante2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Acompañante2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Acompañante2.setText("Actualizar  Acompañante");
        jPanel4.add(btn_Acompañante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        btn_Bebida2.setBackground(new java.awt.Color(0, 0, 0));
        btn_Bebida2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Bebida2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bebida2.setText("Actualizar bebida");
        jPanel4.add(btn_Bebida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        btn_Postre2.setBackground(new java.awt.Color(0, 0, 0));
        btn_Postre2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Postre2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Postre2.setText("Actualizar postre");
        jPanel4.add(btn_Postre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripcion");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 329, -1, -1));

        jTextField_Codigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Codigo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextField_Codigo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 106, 214, -1));

        jTextField_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextField_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 153, 214, -1));

        jTextArea_Descripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_Descripcion.setColumns(20);
        jTextArea_Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextArea_Descripcion.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_Descripcion.setLineWrap(true);
        jTextArea_Descripcion.setRows(5);
        jTextArea_Descripcion.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea_Descripcion);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 214, -1));

        jTextField_Precio.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Precio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextField_Precio.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 325, 214, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Acompañante1;
    public javax.swing.JButton btn_Acompañante2;
    public javax.swing.JButton btn_Bebida1;
    public javax.swing.JButton btn_Bebida2;
    public javax.swing.JButton btn_Carta1;
    public javax.swing.JButton btn_Carta2;
    public javax.swing.JButton btn_Postre1;
    public javax.swing.JButton btn_Postre2;
    public javax.swing.JButton btn_Volver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTable jTable_Acompañante1;
    public javax.swing.JTable jTable_Bebida1;
    public javax.swing.JTable jTable_Carta1;
    public javax.swing.JTable jTable_Postre1;
    public javax.swing.JTextArea jTextArea_Descripcion;
    public javax.swing.JTextField jTextField_Codigo;
    public javax.swing.JTextField jTextField_Nombre;
    public javax.swing.JTextField jTextField_Precio;
    // End of variables declaration//GEN-END:variables
}
