/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Andrés Lombo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        setTitle("Menu principal");

        try {
            setIconImage(new ImageIcon(getClass().getResource("/javax/swing/plaf/metal/icons/ocean/computer.gif")).getImage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Personal = new javax.swing.JButton();
        btn_Ventas = new javax.swing.JButton();
        btn_Proveedores = new javax.swing.JButton();
        btn_Inventarios = new javax.swing.JButton();
        btn_Carta = new javax.swing.JButton();
        btn_Reservas = new javax.swing.JButton();
        btn_Cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(25, 23, 23));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 0, 0), null, null));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bar_Log.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        Btn_Personal.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Personal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Btn_Personal.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        Btn_Personal.setText("Gestión de personal");
        Btn_Personal.setBorderPainted(false);
        Btn_Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PersonalActionPerformed(evt);
            }
        });

        btn_Ventas.setBackground(new java.awt.Color(255, 255, 255));
        btn_Ventas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Ventas.setForeground(new java.awt.Color(0, 0, 0));
        btn_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventas.png"))); // NOI18N
        btn_Ventas.setText("Gestión de ventas");
        btn_Ventas.setBorderPainted(false);

        btn_Proveedores.setBackground(new java.awt.Color(255, 255, 255));
        btn_Proveedores.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Proveedores.setForeground(new java.awt.Color(0, 0, 0));
        btn_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        btn_Proveedores.setText("Gestión de proveedores");
        btn_Proveedores.setBorderPainted(false);

        btn_Inventarios.setBackground(new java.awt.Color(255, 255, 255));
        btn_Inventarios.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Inventarios.setForeground(new java.awt.Color(0, 0, 0));
        btn_Inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        btn_Inventarios.setText("Gestión de inventarios");
        btn_Inventarios.setBorderPainted(false);

        btn_Carta.setBackground(new java.awt.Color(255, 255, 255));
        btn_Carta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Carta.setForeground(new java.awt.Color(0, 0, 0));
        btn_Carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        btn_Carta.setText("Carta");
        btn_Carta.setBorderPainted(false);

        btn_Reservas.setBackground(new java.awt.Color(255, 255, 255));
        btn_Reservas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Reservas.setForeground(new java.awt.Color(0, 0, 0));
        btn_Reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reserva.png"))); // NOI18N
        btn_Reservas.setText("Gestión de reservas");
        btn_Reservas.setBorderPainted(false);

        btn_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        btn_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        btn_Cliente.setText("Gestión de clientes");
        btn_Cliente.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Personal)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Proveedores))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Cliente)
                                .addGap(27, 27, 27)
                                .addComponent(btn_Reservas)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Ventas)
                            .addComponent(btn_Inventarios)))
                    .addComponent(btn_Carta)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Personal)
                    .addComponent(btn_Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inventarios))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cliente)
                    .addComponent(btn_Ventas)
                    .addComponent(btn_Reservas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Carta)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_PersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Personal;
    public javax.swing.JButton btn_Carta;
    public javax.swing.JButton btn_Cliente;
    public javax.swing.JButton btn_Inventarios;
    public javax.swing.JButton btn_Proveedores;
    public javax.swing.JButton btn_Reservas;
    public javax.swing.JButton btn_Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
