/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Andrés Lombo
 */
public class Personal extends javax.swing.JFrame {

    /**
     * Creates new form Personal
     */
    public Personal() {
        initComponents();
        
        setTitle("Gestion de personal");

        try {
            setIconImage(new ImageIcon(getClass().getResource("/javax/swing/plaf/metal/icons/ocean/computer.gif")).getImage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jT_Cedula = new javax.swing.JTextField();
        jT_Nombre = new javax.swing.JTextField();
        jT_Apellido = new javax.swing.JTextField();
        jT_Celular = new javax.swing.JTextField();
        jT_Comentario = new javax.swing.JTextField();
        jT_Calificacion = new javax.swing.JTextField();
        jDate_Fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Empleado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jT_Cedula1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDate_Fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jT_Cod_Cargo1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_TurnoEmpleado = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jT_Codigo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jT_NombreCargo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jT_Valor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Cargo = new javax.swing.JTable();
        btn_Limpiar = new javax.swing.JButton();
        btn_Ejecutar = new javax.swing.JButton();
        btn_Limpiar1 = new javax.swing.JButton();
        btn_Ejecutar1 = new javax.swing.JButton();
        btn_Limpiar2 = new javax.swing.JButton();
        btn_Ejecutar2 = new javax.swing.JButton();
        Jt_BuscarPersonal = new javax.swing.JTextField();
        jT_BuscarCargo = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jT_Horas = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        btn_Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 23, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bar_Log.jpg"))); // NOI18N

        btn_Volver.setBackground(new java.awt.Color(25, 23, 23));
        btn_Volver.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_Volver.setText("Volver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(504, 504, 504))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 112));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cedula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 161, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 206, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 251, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Celular");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 296, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha Nacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 346, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Comentario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 388, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Calificación (1-5)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 429, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Registrar turno del empleado");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 118, -1, -1));

        jT_Cedula.setBackground(new java.awt.Color(255, 255, 255));
        jT_Cedula.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Cedula.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 160, 160, -1));

        jT_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jT_Nombre.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 205, 160, -1));

        jT_Apellido.setBackground(new java.awt.Color(255, 255, 255));
        jT_Apellido.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Apellido.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 250, 160, -1));

        jT_Celular.setBackground(new java.awt.Color(255, 255, 255));
        jT_Celular.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Celular.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 295, 160, -1));

        jT_Comentario.setBackground(new java.awt.Color(255, 255, 255));
        jT_Comentario.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Comentario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 387, 160, -1));

        jT_Calificacion.setBackground(new java.awt.Color(255, 255, 255));
        jT_Calificacion.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Calificacion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 428, 160, -1));

        jDate_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        jDate_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        jDate_Fecha.setDateFormatString("YYYY-MM-dd");
        jPanel1.add(jDate_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 340, 160, -1));

        jTable_Empleado.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Empleado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Empleado.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Empleado.setEnabled(false);
        jScrollPane1.setViewportView(jTable_Empleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 461, -1, 300));

        jPanel3.setBackground(new java.awt.Color(25, 23, 23));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 128, 8, 744));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ingresar nuevo empleado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cedula");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 164, -1, -1));

        jT_Cedula1.setBackground(new java.awt.Color(255, 255, 255));
        jT_Cedula1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Cedula1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 154, 160, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Fecha");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 199, -1, -1));

        jDate_Fecha1.setBackground(new java.awt.Color(255, 255, 255));
        jDate_Fecha1.setForeground(new java.awt.Color(0, 0, 0));
        jDate_Fecha1.setDateFormatString("YYYY-MM-dd");
        jPanel1.add(jDate_Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 193, 160, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Numero de horas");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 241, -1, -1));

        jT_Cod_Cargo1.setBackground(new java.awt.Color(255, 255, 255));
        jT_Cod_Cargo1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Cod_Cargo1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Cod_Cargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 279, 160, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Codigo cargo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 280, -1, -1));

        jTable_TurnoEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jTable_TurnoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_TurnoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        jTable_TurnoEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_TurnoEmpleado.setEnabled(false);
        jScrollPane2.setViewportView(jTable_TurnoEmpleado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 350, 480, 409));

        jPanel4.setBackground(new java.awt.Color(25, 23, 23));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 128, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Registrar cargos operacionales");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 118, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Codigo cargo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 161, -1, -1));

        jT_Codigo.setBackground(new java.awt.Color(255, 255, 255));
        jT_Codigo.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Codigo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 160, 160, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Nombre");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 206, -1, -1));

        jT_NombreCargo.setBackground(new java.awt.Color(255, 255, 255));
        jT_NombreCargo.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_NombreCargo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_NombreCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 205, 160, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Valor hora");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 251, -1, -1));

        jT_Valor.setBackground(new java.awt.Color(255, 255, 255));
        jT_Valor.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Valor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 250, 160, -1));

        jTable_Cargo.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Cargo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Cargo.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Cargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Cargo.setEnabled(false);
        jScrollPane3.setViewportView(jTable_Cargo);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 295, 370, 463));

        btn_Limpiar.setBackground(new java.awt.Color(25, 23, 23));
        btn_Limpiar.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar.setText("Limpiar");
        jPanel1.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 835, -1, -1));

        btn_Ejecutar.setBackground(new java.awt.Color(25, 23, 23));
        btn_Ejecutar.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ejecutar.setText("Ejecutar");
        jPanel1.add(btn_Ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 835, -1, -1));

        btn_Limpiar1.setBackground(new java.awt.Color(25, 23, 23));
        btn_Limpiar1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Limpiar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar1.setText("Limpiar");
        jPanel1.add(btn_Limpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 834, -1, -1));

        btn_Ejecutar1.setBackground(new java.awt.Color(25, 23, 23));
        btn_Ejecutar1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Ejecutar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ejecutar1.setText("Ejecutar");
        jPanel1.add(btn_Ejecutar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 834, -1, -1));

        btn_Limpiar2.setBackground(new java.awt.Color(25, 23, 23));
        btn_Limpiar2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Limpiar2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar2.setText("Limpiar");
        jPanel1.add(btn_Limpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 834, -1, -1));

        btn_Ejecutar2.setBackground(new java.awt.Color(25, 23, 23));
        btn_Ejecutar2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Ejecutar2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ejecutar2.setText("Ejecutar");
        jPanel1.add(btn_Ejecutar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 834, -1, -1));

        Jt_BuscarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        Jt_BuscarPersonal.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        Jt_BuscarPersonal.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Jt_BuscarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 767, 210, -1));

        jT_BuscarCargo.setBackground(new java.awt.Color(255, 255, 255));
        jT_BuscarCargo.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_BuscarCargo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_BuscarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 764, 210, -1));

        btn_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btn_Buscar.setBorderPainted(false);
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 257, 50, -1));

        jT_Horas.setBackground(new java.awt.Color(255, 255, 255));
        jT_Horas.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jT_Horas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jT_Horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 240, 160, -1));

        Total.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(51, 153, 0));
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 765, 481, 63));

        btn_Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        btn_Actualizar.setBorderPainted(false);
        jPanel1.add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 397, 53, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Jt_BuscarPersonal;
    public javax.swing.JLabel Total;
    public javax.swing.JButton btn_Actualizar;
    public javax.swing.JButton btn_Buscar;
    public javax.swing.JButton btn_Ejecutar;
    public javax.swing.JButton btn_Ejecutar1;
    public javax.swing.JButton btn_Ejecutar2;
    public javax.swing.JButton btn_Limpiar;
    public javax.swing.JButton btn_Limpiar1;
    public javax.swing.JButton btn_Limpiar2;
    public javax.swing.JButton btn_Volver;
    public com.toedter.calendar.JDateChooser jDate_Fecha;
    public com.toedter.calendar.JDateChooser jDate_Fecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jT_Apellido;
    public javax.swing.JTextField jT_BuscarCargo;
    public javax.swing.JTextField jT_Calificacion;
    public javax.swing.JTextField jT_Cedula;
    public javax.swing.JTextField jT_Cedula1;
    public javax.swing.JTextField jT_Celular;
    public javax.swing.JTextField jT_Cod_Cargo1;
    public javax.swing.JTextField jT_Codigo;
    public javax.swing.JTextField jT_Comentario;
    public javax.swing.JTextField jT_Horas;
    public javax.swing.JTextField jT_Nombre;
    public javax.swing.JTextField jT_NombreCargo;
    public javax.swing.JTextField jT_Valor;
    public javax.swing.JTable jTable_Cargo;
    public javax.swing.JTable jTable_Empleado;
    public javax.swing.JTable jTable_TurnoEmpleado;
    // End of variables declaration//GEN-END:variables
}
