/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Andrés Lombo
 */
public class Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
        
        setTitle("Gestion de reservas");

        try {
            setIconImage(new ImageIcon(getClass().getResource("/javax/swing/plaf/metal/icons/ocean/computer.gif")).getImage());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        btn_Cliente = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Reserva = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cliente = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Cuenta = new javax.swing.JTable();
        jDate_Fecha = new com.toedter.calendar.JDateChooser();
        jTextField_Valor = new javax.swing.JTextField();
        btn_Reserva = new javax.swing.JButton();
        btn_Pedido = new javax.swing.JButton();
        btn_Pagar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Cliente = new javax.swing.JTextField();
        jTextField_Factura = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jLabel_Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 23, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bar_Log.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 97));

        btn_Volver.setBackground(new java.awt.Color(25, 23, 23));
        btn_Volver.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_Volver.setText("Volver");
        jPanel2.add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_Cliente.setBackground(new java.awt.Color(25, 23, 23));
        btn_Cliente.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cliente.setText("Cliente");
        jPanel2.add(btn_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        btn_Limpiar.setBackground(new java.awt.Color(25, 23, 23));
        btn_Limpiar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar.setText("Limpiar");
        jPanel2.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1101, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 106, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Valor reserva");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, -1, -1));

        jTable_Reserva.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Reserva.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Reserva.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Reserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Reserva);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 106, 719, 172));

        jTable_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Cliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, 359, 157));

        jTable_Cuenta.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Cuenta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable_Cuenta.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Cuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable_Cuenta);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 284, 719, 157));

        jDate_Fecha.setBackground(new java.awt.Color(255, 255, 255));
        jDate_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        jDate_Fecha.setDateFormatString("YYYY-MM-dd");
        jDate_Fecha.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jPanel1.add(jDate_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 106, 218, -1));

        jTextField_Valor.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Valor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextField_Valor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 155, 218, -1));

        btn_Reserva.setBackground(new java.awt.Color(0, 0, 0));
        btn_Reserva.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Reserva.setForeground(new java.awt.Color(255, 255, 255));
        btn_Reserva.setText("Cargar Reserva");
        jPanel1.add(btn_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        btn_Pedido.setBackground(new java.awt.Color(0, 0, 0));
        btn_Pedido.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Pedido.setForeground(new java.awt.Color(255, 255, 255));
        btn_Pedido.setText("Cargar Pedido");
        jPanel1.add(btn_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        btn_Pagar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Pagar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Pagar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Pagar.setText("Pagar");
        jPanel1.add(btn_Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cliente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 206, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Pedido");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 253, -1, -1));

        jTextField_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextField_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 202, 218, -1));

        jTextField_Factura.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Factura.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTextField_Factura.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 249, 218, -1));

        btn_Buscar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Buscar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Buscar.setText("Buscar");
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel_Total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Total.setForeground(new java.awt.Color(153, 153, 0));
        jPanel1.add(jLabel_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 350, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar;
    public javax.swing.JButton btn_Cliente;
    public javax.swing.JButton btn_Limpiar;
    public javax.swing.JButton btn_Pagar;
    public javax.swing.JButton btn_Pedido;
    public javax.swing.JButton btn_Reserva;
    public javax.swing.JButton btn_Volver;
    public com.toedter.calendar.JDateChooser jDate_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel_Total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable_Cliente;
    public javax.swing.JTable jTable_Cuenta;
    public javax.swing.JTable jTable_Reserva;
    public javax.swing.JTextField jTextField_Cliente;
    public javax.swing.JTextField jTextField_Factura;
    public javax.swing.JTextField jTextField_Valor;
    // End of variables declaration//GEN-END:variables
}
